export const CHANGE_USERNAME_ACTION = "CHANGE_USERNAME_ACTION";
export const CHANGE_USER_STATUS_ACTION = "CHANGE_USER_STATUS_ACTION";
export const CHANGE_SELECTED_TAB_ACTION = "CHANGE_SELECTED_TAB_ACTION";
